In [91]:
import numpy as np
from graph import Graph
from sparsifiers import RandomSparsifier
from algorithms.pagerank import pagerank
import timeit

In [78]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [ ]:
results = dict()

for n in range(20, 5000, 100):
    results[n] = {'initial': [],
                 'sparse': []}
    g = Graph(n)
    adj_mat = np.random.choice([0, 1], size=[n, n], p=[0.4, 0.6])
    np.fill_diagonal(adj_mat, 0, wrap=False)
    g.adj_mat_to_adj_list(adj_mat)
    results[n]['initial'].append(timeit.timeit('pagerank(g, 1e-6)', globals=globals(), number=7))
    results[n]['initial'].append(pagerank(g, 1e-6))

    sp = RandomSparsifier(0.5)
    sp.to_sparse(g)
    results[n]['sparse'].append(timeit.timeit('pagerank(g, 1e-6)', globals=globals(), number=7))
    results[n]['sparse'].append(pagerank(g, 1e-6))

In [98]:
results

{20: {'initial': [0.004698000000644242,
   array([0.05978586, 0.0510115 , 0.05036984, 0.03952433, 0.06338469,
          0.05894937, 0.0631416 , 0.04590667, 0.05132036, 0.0283693 ,
          0.04788398, 0.04373946, 0.03398564, 0.05783289, 0.03744736,
          0.05752671, 0.04164056, 0.07353795, 0.04638057, 0.04826137])],
  'sparse': [0.0036574000005202834,
   array([0.04816482, 0.03195238, 0.06849373, 0.03697086, 0.07324701,
          0.04710958, 0.06234003, 0.04629872, 0.03351899, 0.01365663,
          0.05649333, 0.05871138, 0.03507822, 0.06067128, 0.04762603,
          0.06767904, 0.05258631, 0.06173289, 0.05429739, 0.04337138])]},
 40: {'initial': [0.010055799999463488,
   array([0.03352182, 0.01940668, 0.02352602, 0.01950353, 0.02899889,
          0.01741334, 0.01767875, 0.01803805, 0.02658938, 0.02050829,
          0.01712038, 0.0210454 , 0.01676469, 0.02525547, 0.02362893,
          0.02320187, 0.02005775, 0.02857384, 0.02577967, 0.02695764,
          0.03139177, 0.02907722, 0.0

In [ ]:
n_v = results.keys()
sparse_time = [v['sparse'][0] for v in results.values()]
error = [np.linalg.norm(v['sparse'][1] -  for v in results.values()]